# Generated by Django 5.1.7 on 2025-07-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='is_active',
        ),
        migrations.AddField(
            model_name='match',
            name='secret',
            field=models.CharField(default=' ', max_length=32),
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('playing', 'Playing'), ('finished', 'Finished')], default='waiting', max_length=10),
        ),
    ]
